### ISSUE TITLE
Consertar acentos nos nomes das publicações 

### ISSUE THREAD

**Issue by anacarlagb** [opus-research/opus-research.github.io#4]

**Comment by anacarlagb** [comment]
@danieljbc essa issue, vc consertou na mão mesmo? Por que tem uns nomes ainda sem acento. Olha o exemplo ai. 
![image](https://user-images.githubusercontent.com/1778853/122555531-cbab7e00-d010-11eb-935a-14c2765c3a18.png)

**Comment by danieljbc** [comment]
Eu fiz um script que consertava os acentos que estivessem naquele formato de comando do latex (e.g. `\^{o}`). 
Como não olhei todos os casos manualmente, então casos assim onde os nomes estavam sem acento ficaram faltando mesmo. 
Também vi agora alguns casos de artigos antigos cujo bibtex deu erro de compilação. Vou arrumar esses com erro de compilação e esse caso que você enviou aí. Se encontrar mais algum só enviar aqui que eu arrumo também.

**Comment by anacarlagb** [comment]
Conferi e vi que já tá tudo ok, fechei essa issue.
